/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fr.nicopico.nirvanawear

import fr.nicopico.nirvanawear.models.AuthToken
import fr.nicopico.nirvanawear.models.json.AuthResponse
import io.ktor.client.*
import io.ktor.client.call.*
import io.ktor.client.engine.*
import io.ktor.client.plugins.contentnegotiation.*
import io.ktor.client.request.forms.*
import io.ktor.http.*
import io.ktor.serialization.kotlinx.json.*
import kotlinx.serialization.json.Json

interface NirvanaClient {
    suspend fun authenticate(login: String, password: String): AuthToken
}

class NirvanaClientKtor(
    engine: HttpClientEngine
) : NirvanaClient {
    private val httpClient = HttpClient(engine) {
        install(ContentNegotiation) {
            json(json = Json {
                ignoreUnknownKeys = true
            })
        }
    }

    override suspend fun authenticate(login: String, password: String): AuthToken {
        val response =  httpClient.submitForm(
            url = "https://api.nirvanahq.com/?api=rest",
            formParameters = Parameters.build {
                append("method", "auth.new")
                append("u", login)
                append("p", password)
            },
        )
        return response.body<AuthResponse>().token
    }
}
